BMS/BMS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('apone.urls', namespace='apone')),
]

BMS/apone/urls.py
from django.conf.urls import url
from . import views

app_name = "apone"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    # 作家url
    url(r'^writers', views.writers, name="writers"),
    url(r'^add_writer/', views.add_writer, name="add_writer"),
    url(r'^remove_writer', views.remove_writer, name="remove_writer"),
    url(r'^edite_writer', views.edite_writer, name="edite_writer"),

    url(r'books/', views.books, name="books"),
    url(r'add_book/', views.add_book, name="add_book"),
    url(r'remove_book/(\d+)', views.remove_book, name="remove_book"),
    url(r'edite_book/(\d+)', views.edite_book, name="edite_book"),

    url(r'publishers/', views.publishers, name="publishers"),
    url(r'^add_publisher/', views.add_publisher, name="add_publisher"),
    url(r'^remove_publisher', views.remove_publisher, name="remove_publisher"),
    url(r'^edite_publisher', views.edite_publisher, name="edite_publisher"),
]

BMS/apone/models.py
from django.db import models


class Books(models.Model):
    name = models.CharField(max_length=32)
    pub_date = models.DateField(auto_now_add=False)
    pub_company = models.ForeignKey("Publishers", on_delete=models.CASCADE)
    main_content = models.TextField()
    price = models.IntegerField()

    def __str__(self):
        return self.name


class Writers(models.Model):
    name = models.CharField(max_length=32)
    books = models.ManyToManyField("Books")

    def __str__(self):
        return self.name


class Publishers(models.Model):
    name = models.CharField(max_length=32)

    # writers = models.ManyToManyField("Writers")

    def __str__(self):
        return self.name

BMS/apone/views.py
from django.shortcuts import render, redirect
from apone import models
from apone.models import Writers
from django.urls import reverse


def index(request):
    return render(request, "index.html")


# writers
def writers(request):
    obj = models.Writers.objects.all()
    # obj1 = models.Writers.objects.get(id=1)
    # writer_books = obj1.books_set.get()
    # 这里想要实现作者有哪些书，没能成功对应
    return render(request, "writers.html", {"writers": obj})


def add_writer(request):
    if request.method != "POST":
        return render(request, "add_writer.html")
    else:
        name = request.POST.get("writer_name")
        new_name = models.Writers.objects.create(name=name)
        new_name.save()
        return redirect("apone:writers")


def remove_writer(request):
    dele_obj = request.GET.get("id")
    obj = models.Writers.objects.get(id=dele_obj)
    obj.delete()
    return redirect("apone:writers")


def edite_writer(request):
    if request.method == "POST":
        new_writer_id = request.POST.get("writer_id")
        new_writer_name = request.POST.get("writer_name")
        obj = Writers.objects.get(id=new_writer_id)
        obj.name = new_writer_name
        obj.save()
        return redirect("/writers/")
    edite_id = request.GET.get("id")
    edite_obj = Writers.objects.get(id=edite_id)
    return render(request, "edite_writer.html", {"edite_writer": edite_obj})


# books
def books(request):
    obj = models.Books.objects.all()
    return render(request, "books.html", {"books": obj})


def add_book(request):
    writers_obj = models.Writers.objects.all()
    publisher_list = models.Publishers.objects.all()
    context = {"writers_list": writers_obj, "publisher_list": publisher_list}

    if request.method != "POST":
        return render(request, "add_book.html", context)
    name = request.POST.get("book_name")
    writer = request.POST.getlist("writer_name")
    publisher = request.POST.get("publisher_id")
    new_pub_date = request.POST.get("pub_date")
    main_content = request.POST.get("main_content")

    new_writers = models.Books.objects.create(name=name, pub_date=new_pub_date, main_content=main_content,
                                              pub_company_id=publisher)
    # 一本书对应多个作者
    new_writers.writer.set(writer)
    new_writers.save()
    return redirect("/books/")


def remove_book(request, arg):
    # print(arg)
    # remove_id = request.GET.get("id")
    remove_obj = models.Books.objects.get(id=arg)
    remove_obj.delete()
    return redirect("apone:books")


def edite_book(request, arg):
    if request.method != "POST":
        # 之前是通过url连接传递id值，所以需要get（）一下
        # edite_id = request.GET.get("id")
        edite_obj = models.Books.objects.get(id=arg)
        writers_obj = models.Writers.objects.all()
        publisher_list = models.Publishers.objects.all()
        context = {"books_list": edite_obj, "writers_list": writers_obj, "publisher_list": publisher_list}
        return render(request, "edite_book.html", context)
    book_id = request.POST.get("book_id")
    book_name = request.POST.get("book_name")
    writer = request.POST.getlist("writer_id")
    publisher = request.POST.get("publisher_id")
    new_pub_date = request.POST.get("pub_date")
    main_content = request.POST.get("main_content")
    # 获取要修改的对象
    new_edite_obj = models.Books.objects.get(id=book_id)
    new_edite_obj.name = book_name
    # 修改多对多字段时要用<多对多字段> .set(<新值>)
    new_edite_obj.writer.set(writer)
    new_edite_obj.pub_company.name = publisher
    new_edite_obj.pub_date = new_pub_date
    new_edite_obj.main_content = main_content
    new_edite_obj.save()
    # 这两种方式都可以取到
    # return redirect("apone:books")
    url = reverse("apone:books")
    return redirect(url)


def publishers(request):
    obj = models.Publishers.objects.all()
    return render(request, "publishers.html", {"publishers": obj})


def add_publisher(request):
    if request.method != "POST":
        return render(request, "add_publisher.html")
    else:
        name = request.POST.get("publisher_name")
        new_name = models.Publishers.objects.create(name=name)
        new_name.save()
        return redirect("apone:publishers")


def remove_publisher(request):
    dele_obj = request.GET.get("id")
    obj = models.Publishers.objects.get(id=dele_obj)
    obj.delete()
    return redirect("apone:publishers")


def edite_publisher(request):
    if request.method == "POST":
        publisher_id = request.POST.get("publisher_id")
        new_publisher_name = request.POST.get("publisher_name")
        obj = models.Publishers.objects.get(id=publisher_id)
        obj.name = new_publisher_name
        obj.save()
        return redirect("/publishers/")
    else:
        edite_id = request.GET.get("id")
        edite_obj = models.Publishers.objects.get(id=edite_id)

    return render(request, "edite_publisher.html", {"edite_publisher": edite_obj})

BMS/templates/add_book.html
{% extends "base.html" %}
{% block title %} add_book {% endblock %}
{% block book %}active{% endblock %}
{% block content %}

    <div class="myform">
        <form class="form-horizontal" action="/add_book/" method="POST">
            <div class="row">

                <div class="form-group">
                    <label for="student_name" class="col-sm-2 control-label">书名：</label>
                    <div class="col-sm-9">
                        <input type="text" name="book_name" id="student_name" class="form-control ">
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="form-group">
                    <label for="class_name" class="col-sm-2 control-label">作者:</label>
                    <div class="col-sm-9">
                        <select multiple name="writer_name" class="form-control">
                            {% for writer in writers_list %}

                                <option value="{{ writer.id }}">{{ writer.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label for="class_name" class="col-sm-2 control-label">出版社:</label>
                    <div class="col-sm-9">
                        <select name="publisher_id" class="form-control">
                            {% for publisher in publisher_list %}
                                <option value="{{ publisher.id }}">{{ publisher.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="student_name" class="col-sm-2 control-label">出版日期：</label>
                <div class="col-sm-9">
                    <input type="text" name="pub_date" id="student_name" class="form-control ">
                </div>
            </div>
            <div class="form-group">
                <label for="student_name" class="col-sm-2 control-label">主要内容：</label>
                <div class="col-sm-9">
                    <input type="text" name="main_content" id="student_name" class="form-control ">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-7">
                    <input type="submit" class="btn btn-primary" value="提交">

                </div>
        </form>
    </div>
{% endblock %}

BMS/templates/add_publisher.html
{% extends "base.html" %}
{% block title %} add_publisher {% endblock %}
{% block publisher %}active{% endblock %}
{% block content %}
    <div class="myform">
        <form class="form-horizontal" action="/add_publisher/" method="POST">

            <div class="row">

                <div class="form-group">
                    <label for="student_name" class="col-sm-2 control-label">出版社名称：</label>
                    <div class="col-sm-9">
                        <input type="text" name="publisher_name" id="student_name" class="form-control ">
                    </div>
                </div>

            </div>

            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-7">
                    <input type="submit" class="btn btn-primary" value="提交">

                </div>
        </form>
    </div>
{% endblock %}

BMS/templates/add_writer.html
{% extends "base.html" %}
{% block title %} add_writer {% endblock %}
{% block writer %}active{% endblock %}
{% block content %}
    <div class="myform">
        <form class="form-horizontal" action="/add_writer/" method="POST">
            <div class="row">

                <div class="form-group">
                    <label for="student_name" class="col-sm-2 control-label">作家姓名：</label>
                    <div class="col-sm-9">
                        <input type="text" name="writer_name" id="student_name" class="form-control ">
                    </div>
                </div>

            </div>

            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-7">
                    <input type="submit" class="btn btn-primary" value="提交">

                </div>
        </form>
    </div>
{% endblock %}

BMS/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap.css' %}">
</head>
<style>
    .mynav {
        padding-bottom: 20px;
    }
</style>
<body>

<div class="mynav">
    <ul class="nav nav-tabs">
        <li role="presentation" class={% block index %}{% endblock %}><a href='{% url "apone:index" %}'>主页</a></li>
        <li role="presentation" class={% block book %}{% endblock %}><a href='{% url "apone:books" %}'>图书管理</a></li>
        <li role="presentation" class={% block publisher %}{% endblock %}><a
                href='{% url "apone:publishers" %}'>出版社管理</a></li>
        <li role="presentation" class={% block writter %}{% endblock %}><a href='{% url "apone:writers" %}'>作者管理</a>
        </li>
    </ul>
</div>

<div class="container">
    {% block content %} {% endblock content %}
</div>

</body>
<script src="{% static 'jquery-3.3.1.js' %}"></script>
<script src="{% static 'bootstrap.js' %}"></script>
</html>

BMS/templates/books.html
{% extends "base.html" %}
{% block title %} book_list {% endblock %}
{% block book %}active{% endblock %}
{% block content %}
    {#页头#}
    <div class="page-header">
        <h1>图书管理系统
            <small>图书列表</small>
        </h1>
        {#面板#}
        <div class="panel panel-primary">
            <div class="panel-heading">图书列表</div>
            <div class="panel-body">
                {# 搜索#}
                <div class="row search_row " style="padding-bottom: 10px;">
                    <div class="col-md-4">
                        <form class="form-inline">
                            <div class="form-group">
                                <label class="sr-only" for="exampleInputAmount"></label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="exampleInputAmount" placeholder="搜索">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-default">搜索</button>
                        </form>

                    </div>
                    <div class="col-md-2  pull-right">
                        <a href="/add_book/">
                            <button type="button" class="btn btn-primary mybutton">
                                新增图书
                            </button>
                        </a>
                    </div>
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>book id</th>
                        <th>book name</th>
                        <th>book writer</th>
                        <th>publisher</th>
                        <th>published date</th>
                        <th>main content</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for book in books %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ book.id }}</td>
                            <td>{{ book.name }}</td>

                            <td>
                                {% for writer in book.writer.all %}
                                    {{ writer.name }}
                                {% endfor %}
                            </td>
                            <td>{{ book.pub_company.name }}</td>
                            <td>{{ book.pub_date |date:"Y-m-d" }}</td>
                            <td>{{ book.main_content }}</td>
                            <td>
                                <a href="/remove_book/{{ book.id }}" class="btn btn-default">
                                    删除
                                </a>
                                <a href="/edite_book/{{ book.id }}" class="btn btn-default">
                                    编辑
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {# 分页#}
                <nav aria-label="Page navigation " class="pull-right">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>



{% endblock %}

BMS/templates/edite_book.html
{% extends "base.html" %}
{% block title %} edite_book {% endblock %}
{% block book %}active{% endblock %}
{% block content %}

    <div class="myform">
        <form class="form-horizontal" action="{% url 'apone:edite_book' books_list.id %}" method="POST">
            <div class="row">
                <div class="form-group hidden">
                    <label for="student_name" class="col-sm-2 control-label">id：</label>
                    <div class="col-sm-9">
                        <input type="text" name="book_id" id="student_name" class="form-control "
                               value="{{ books_list.id }}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label for="student_name" class="col-sm-2 control-label">书名：</label>
                    <div class="col-sm-9">
                        <input type="text" name="book_name" id="student_name" class="form-control "
                               value="{{ books_list.name }}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label for="class_name" class="col-sm-2 control-label">作者:</label>
                    <div class="col-sm-9">
                        <select multiple name="writer_id" class="form-control">
                            {% for writer in writers_list %}
                                {% if writer == books_list.writer %}
                                    <option selected value="{{ writer.id }}">{{ writer.name }}</option>
                                {% else %}
                                    <option value="{{ writer.id }}">{{ writer.name }}</option>
                                {% endif %}

                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label for="class_name" class="col-sm-2 control-label">出版社:</label>
                    <div class="col-sm-9">
                        <select name="publisher_id" class="form-control">
                            {% for publisher in publisher_list %}

                                {% if publisher == books_list.pub_company %}
                                    <option selected value="{{ publisher.id }}">{{ publisher.name }}</option>
                                {% else %}
                                    <option value="{{ publisher.id }}">{{ publisher.name }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label for="student_name" class="col-sm-2 control-label">出版日期：</label>
                    <div class="col-sm-9">
                        <input type="text" name="pub_date"
                               id="student_name" class="form-control "
                               value="{{ books_list.pub_date |date:"Y-m-d" }}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label for="student_name" class="col-sm-2 control-label">主要内容:</label>
                    <div class="col-sm-9">
                        <input type="text" name="main_content" id="student_name" class="form-control "
                               value="{{ books_list.main_content }}">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-7">
                    <input type="submit" class="btn btn-primary" value="提交">

                </div>
        </form>
    </div>
{% endblock %}

BMS/templates/edite_publisher.html
{% extends "base.html" %}
{% block title %} edite_publisher {% endblock %}
{% block publisher %}active{% endblock %}
{% block content %}
    <div class="myform">
        <form class="form-horizontal" action="{% url 'apone:edite_publisher' %}" method="POST">
            <div class="form-group hidden">
                <label for="input11" class="col-sm-2 control-label">ID：</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control"
                           id="input11" name="publisher_id"
                           value="{{ edite_publisher.id }}">
                </div>
            </div>
            <div class="row">

                <div class="form-group">
                    <label for="student_name" class="col-sm-2 control-label">作家姓名：</label>
                    <div class="col-sm-9">
                        <input type="text" name="publisher_name" id="student_name" class="form-control "
                               value="{{ edite_publisher.name }}">
                    </div>
                </div>

            </div>

            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-7">
                    <input type="submit" class="btn btn-primary" value="提交">

                </div>
        </form>
    </div>
{% endblock %}

BMS/templates/edite_writer.html
{% extends "base.html" %}
{% block title %} add_writer {% endblock %}
{% block writer %}active{% endblock %}
{% block content %}
    <div class="myform">
        <form class="form-horizontal" action="{% url 'apone:edite_writer' %}" method="POST">
            <div class="row">
                <div class="form-group hidden">
                    <label for="student_name" class="col-sm-2 control-label">ID：</label>
                    <div class="col-sm-9">
                        <input type="text" name="writer_id" id="student_name" class="form-control "
                               value="{{ edite_writer.id }}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <label for="student_name" class="col-sm-2 control-label">作家姓名：</label>
                    <div class="col-sm-9">
                        <input type="text" name="writer_name" id="student_name" class="form-control "
                               value="{{ edite_writer.name }}">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-5 col-sm-7">
                    <input type="submit" class="btn btn-primary" value="提交">

                </div>
        </form>
    </div>
{% endblock %}

BMS/templates/index.html
{% extends "base.html" %}
{% block title %} index {% endblock %}
{% block index %}active{% endblock %}
{% block content %}
    <div class="jumbotron">
        <h1> 欢迎来到大V图书管理系统</h1>
    </div>
{% endblock %}

BMS/templates/publishers.html
{% extends "base.html" %}
{% block title %} publisher_list {% endblock %}
{% block publisher %}active{% endblock %}
{% block content %}
    {#页头#}
    <div class="page-header">
        <h1>图书管理系统
            <small>出版社列表</small>
        </h1>
        {#面板#}
        <div class="panel panel-primary">
            <div class="panel-heading">出版社列表</div>
            <div class="panel-body">
                {# 搜索#}
                <div class="row search_row " style="padding-bottom: 10px;">
                    <div class="col-md-4">
                        <form class="form-inline">
                            <div class="form-group">
                                <label class="sr-only" for="exampleInputAmount"></label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="exampleInputAmount" placeholder="搜索">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-default">搜索</button>
                        </form>

                    </div>
                    <div class="col-md-2  pull-right">
                        <a href="/add_publisher/">
                            <button type="button" class="btn btn-primary mybutton">
                                新增出版社
                            </button>
                        </a>
                    </div>
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>publisher id</th>
                        <th>publisher name</th>
                        {#                        <th>books</th>#}
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for publisher in publishers %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ publisher.id }}</td>
                            <td>{{ publisher.name }}</td>
                            {#                            <td>{{ book_list.name}}</td>#}
                            <td>
                                <a href="/remove_publisher?id={{ publisher.id }}">
                                    <button class="btn btn-default"> 删除</button>
                                </a>
                                <a href="/edite_publisher?id={{ publisher.id }}">
                                    <button class="btn btn-default">编辑</button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {# 分页#}
                <nav aria-label="Page navigation " class="pull-right">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>



{% endblock %}

BMS/templates/writers.html
{% extends "base.html" %}
{% block title %} writter_list {% endblock %}
{% block writter %}active{% endblock %}
{% block content %}
    {#页头#}
    <div class="page-header">
        <h1>图书管理系统
            <small>作家列表</small>
        </h1>
        {#面板#}
        <div class="panel panel-primary">
            <div class="panel-heading">作家列表</div>
            <div class="panel-body">
                {# 搜索#}
                <div class="row search_row " style="padding-bottom: 10px;">
                    <div class="col-md-4">
                        <form class="form-inline">
                            <div class="form-group">
                                <label class="sr-only" for="exampleInputAmount"></label>
                                <div class="input-group">
                                    <input type="text" class="form-control" id="exampleInputAmount" placeholder="搜索">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-default">搜索</button>
                        </form>

                    </div>
                    <div class="col-md-2  pull-right">
                        <a href="/add_writer/">
                            <button type="button" class="btn btn-primary mybutton">
                                新增作家
                            </button>
                        </a>
                    </div>
                </div>

                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>writer id</th>
                        <th>writer name</th>
                        {#                        <th>books</th>#}
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for writer in writers %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ writer.id }}</td>
                            <td>{{ writer.name }}</td>
                            {#                            <td>{{ book_list.name}}</td>#}
                            <td>
                                <a href="/remove_writer?id={{ writer.id }}">
                                    <button class="btn btn-default"> 删除</button>
                                </a>
                                <a href="/edite_writer?id={{ writer.id }}">
                                    <button class="btn btn-default">编辑</button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {# 分页#}
                <nav aria-label="Page navigation " class="pull-right">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>



{% endblock %}